### ISSUE TITLE
Flight Runway Integration Caveat

### ISSUE THREAD

**Issue by ColonelPanics** [openflighthpc/power-server#13]
With Flight Runway & systemd integration an environment file is created at `/opt/flight/etc/power-server.conf` which is used to set the `jwt_shared_secret`.

The slight issue/caveat/gotcha/inconsistency here is that this file is not looked for or checked by power-server itself so running any commands on the server (e.g. `bin/rake token:user`) will result in an error because "Missing required configuration keys: ["jwt_shared_secret"]".

Would it be worth ensuring that the application itself will use this config file if it's present?

**Comment by WilliamMcCumstie** [comment]
The `/opt/flight/etc/power-server.conf` is used by `systemd` to configure the application. It is not a configuration tool for the application itself. As such the `app` should not load the keys automatically.

This sounds more like an integration issue, which should be handled during the rpm build or manually sourcing the file before running the rake task.

Something like:

```
set -a
source /opt/flight/etc/power-server.conf
set +a
bin/rake token:user
``

**Comment by ColonelPanics** [comment]
Thanks for the feedback, `set -a` is super helpful for the problem I was trying to fix/understand when logging this question.

Reference to where this came in useful - https://github.com/openflighthpc/openflight-omnibus-builder/commit/edf9f3199e6c198787ca8a9be40dac82dd836c05
